name: Weather Logger


on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch: # manual trigger option

jobs:
  log-weather:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install requests
      run: python -m pip install requests

    - name: Run weather logging script
      run: python Weather_Logger\weather_logger.py

    - name: Commit updated CSV file
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add Weather_Logger\weather_log.csv
        git commit -m "Update weather_log.csv - $(date -u +"%Y-%m-%d %H:%M:%S")" || echo "No changes to commit"
        git push
